nelmio_cors:
    # defaults:
    #     origin_regex: true
    #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     max_age: 3600
    # paths:
    #     '^/': ~
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PATCH', 'GET', 'DELETE', 'PUT', 'OPTIONS']
        expose_headers: []
        max_age: 1
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PATCH', 'GET', 'DELETE', 'PUT', 'OPTIONS']
            max_age: 1